"""Add execution_time to message, update reaction and content optional in message_comment

Revision ID: 3a25101659b5
Revises: 1fae72fd9ec8
Create Date: 2025-02-26 12:48:17.696373

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3a25101659b5'
down_revision = '1fae72fd9ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('execution_time', sa.Integer(), nullable=True))
    op.alter_column('message_comment', 'reaction',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('message_comment', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_comment', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('message_comment', 'reaction',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('message', 'execution_time')
    # ### end Alembic commands ###
