"""Add title and description to chartoom

Revision ID: 4d237adc93fd
Revises: 64d8373396aa
Create Date: 2025-02-26 14:28:10.487940

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4d237adc93fd'
down_revision = '64d8373396aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatroom', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chatroom', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatroom', 'description')
    op.drop_column('chatroom', 'title')
    # ### end Alembic commands ###
