"""Move comment_reaction and comment_content to message

Revision ID: 64d8373396aa
Revises: 3a25101659b5
Create Date: 2025-02-26 13:21:44.251933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64d8373396aa'
down_revision = '3a25101659b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_comment')
    op.add_column('message', sa.Column('comment_reaction', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('message', sa.Column('comment_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'comment_content')
    op.drop_column('message', 'comment_reaction')
    op.create_table('message_comment',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chatroom_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatroom.id'], name='message_comment_chatroom_id_fkey'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='message_comment_message_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_comment_pkey')
    )
    # ### end Alembic commands ###
